name: Build and test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4.0.0
        with:
          python-version: '3.x'
      - name: Install pre-commit
        run: pip install pre-commit
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Build
        run: make build
      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest
      - name: Run pre-commit checks
        run: make check
      - name: Test
        run: make test
